### PR TITLE
improve participant configuration with participant lists

### LINKED ISSUE #7: Participant Lists
https://xd.adobe.com/view/564f95d4-3039-489e-aabe-6dc0170e5f2a-031c/

### PR DESCRIPTION
**Pull request by Connoropolous**
closes #7 

- [x] plumbing for participant lists
- [x] public link option configuration
- [x] participant list selector
- [x] participant list saver
- [x] add generic Modal
- [x] persist the selected existing list in the formData

Screen Shot 2019-12-26 at 8 55 33 PM
Screen Shot 2019-12-26 at 8 55 33 PM
Screen Shot 2019-12-28 at 9 40 03 AM
Screen Shot 2019-12-28 at 9 39 45 AM

### CODE REVIEW

**Comment by Connoropolous** [comment]
Great question. I wonder how useful it would be to have both no as a simultaneous option...

It is currently implemented as a one or the other thing, although if you pick from a list, you'll then still be able to edit the particpant list without affecting that original list

**Comment by Bortseb** [comment]
I could see the need for multiple, say for example on a live call... Where
maybe you have a list you want to import, but it turns out that doesn't yet
contain everyone on the call... So you want that list, plus a few people
who maybe want to opt-in at a web link last minute... and then, maybe at
the same time someone who's maybe phoning in, wants their cell number to be
added manually by the facilitator...

Thinking through this also made me think it would likely be useful to
automatically save participant lists for facilitators, that have automatic
names that can be changed, and then used again later. For example an
automated list from anyone who opt-ed in through a web form... or an
automated list of the entire group who participated in a previous round of
a process... so that these named participant lists can then just be
re-input into later rounds of processes.

ha ha... this all begins to sort of feel like email lists... that people
might want to opt-out of later... for example in a longer-term process that
continues on asynchronously.

**Comment by Connoropolous** [comment]
yeah I can see use cases for multiple as well... I think it will be explored as a follow up, since it would require a bit of redesign

**Comment by Connoropolous** [comment]
Good enough to move on with :)

followups for this would involve 
#19 
and
#11

**Comment by Connoropolous** [comment]
also later a 'Delete Participant List' option of course

**Comment by Connoropolous** [comment]
For the record, total time spent:

~ 9 hours

Screen Shot 2019-12-28 at 12 16 26 PM

**Pull request merged**
